"""Evidence AI contracts v1 — the public surface (explicit re-exports only)."""

from .common import (
    CONTRACTS_V1,
    Coding,
    ContractVersion,
    NormalizedQuantity,
    Quantity,
    StrictModel,
)
from .connector import (
    ConnectorDescriptor,
    ConnectorKind,
    ConnectorMeta,
    ConnectorStatus,
    EvidencePassage,
    PassageScores,
    RetrieveResponse,
)
from .document import (
    Chunk,
    CorpusSnapshot,
    Document,
    DocumentVersion,
    EvidenceTier,
    LicenseClass,
    SourceAuthority,
)
from .envelope import (
    MAX_ENVELOPE_BYTES,
    AnswerEnvelope,
    AnswerStatus,
    CheckOutcome,
    CheckResult,
    Citation,
    Flag,
    FlagSeverity,
    Segment,
    SegmentKind,
    SourceKind,
    SourceRef,
)
from .followup import FollowUp, FollowUpAnswerType, FollowUpPriority
from .intent import ClinicalConcept, ClinicalIntent, QuestionType
from .provenance import AnswerProvenance, StageOutcome, StageTrace
from .snapshot import (
    FactOriginKind,
    FactProvenance,
    FactSource,
    FactStatus,
    PatientFact,
    PatientSnapshot,
)
from .stream import (
    AnswerMode,
    AnswerStreamDone,
    AnswerStreamError,
    AnswerStreamEvent,
    AnswerStreamHeader,
    StreamEventKind,
)
from .triage import TriageDecision, TriageOutcome, TriageReason
from .webref import WebSourceRef, WebTrustTier

__all__ = [
    "CONTRACTS_V1",
    "MAX_ENVELOPE_BYTES",
    "AnswerEnvelope",
    "AnswerMode",
    "AnswerProvenance",
    "AnswerStatus",
    "AnswerStreamDone",
    "AnswerStreamError",
    "AnswerStreamEvent",
    "AnswerStreamHeader",
    "CheckOutcome",
    "CheckResult",
    "Chunk",
    "Citation",
    "ClinicalConcept",
    "ClinicalIntent",
    "Coding",
    "ConnectorDescriptor",
    "ConnectorKind",
    "ConnectorMeta",
    "ConnectorStatus",
    "ContractVersion",
    "CorpusSnapshot",
    "Document",
    "DocumentVersion",
    "EvidencePassage",
    "EvidenceTier",
    "FactOriginKind",
    "FactProvenance",
    "FactSource",
    "FactStatus",
    "Flag",
    "FlagSeverity",
    "FollowUp",
    "FollowUpAnswerType",
    "FollowUpPriority",
    "LicenseClass",
    "NormalizedQuantity",
    "PassageScores",
    "PatientFact",
    "PatientSnapshot",
    "Quantity",
    "RetrieveResponse",
    "QuestionType",
    "Segment",
    "SegmentKind",
    "SourceAuthority",
    "SourceKind",
    "SourceRef",
    "StageOutcome",
    "StageTrace",
    "StreamEventKind",
    "StrictModel",
    "TriageDecision",
    "TriageOutcome",
    "TriageReason",
    "WebSourceRef",
    "WebTrustTier",
]
