"""Wire protocol for `medical-dictation.v1`. See docs/api/dictation-ws-v1.md."""

from .codec import (
    BadMessageError,
    PROTOCOL_VERSION,
    SUBPROTOCOL,
    decode_binary,
    decode_text,
    encode_server,
)
from .error_catalogue import ErrorCode
from .messages import (
    AudioFrame,
    ClientMessage,
    EndSession,
    Error,
    Final,
    Heartbeat,
    Partial,
    Pause,
    RefreshToken,
    Resume,
    RetransmitRange,
    ServerMessage,
    SessionStarted,
    SessionTerminated,
    StartSession,
    SwitchSection,
    TokenExpiring,
    VoiceCommand,
    Warning_,
)

__all__ = [
    "AudioFrame",
    "BadMessageError",
    "ClientMessage",
    "EndSession",
    "Error",
    "ErrorCode",
    "Final",
    "Heartbeat",
    "PROTOCOL_VERSION",
    "Partial",
    "Pause",
    "RefreshToken",
    "Resume",
    "RetransmitRange",
    "SUBPROTOCOL",
    "ServerMessage",
    "SessionStarted",
    "SessionTerminated",
    "StartSession",
    "SwitchSection",
    "TokenExpiring",
    "VoiceCommand",
    "Warning_",
    "decode_binary",
    "decode_text",
    "encode_server",
]
